TrackingVaksinApp/Controllers/BPOM/BPOMVaksinController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Net.Http;
using System.Web.Mvc;
using System.Threading.Tasks;
using System.Net.Http.Headers;
using Newtonsoft.Json;
using RestSharp;
using TrackingVaksinApp.BPOMServiceReference;

namespace TrackingVaksinApp.Controllers
{
    public class BPOMVaksinController : Controller
    {
        // GET: BPOMVaksin
        [HttpGet]
        public ActionResult Index()
        {
            if (Session["username"] == null)
                return RedirectToRoute("Autentication", new { controller = "User" });
            EBPOMServiceClient obj = new EBPOMServiceClient();
            Models.ListViewModel viewmodel = new Models.ListViewModel
            {
                bpom_vaksins = obj.GetVaksin(),
                produsens = obj.GetListProdusen()
            };
            return View(viewmodel);
        }

        [HttpPost]
        public ActionResult Index(string no_registrasi,DateTime create_at, string status)
        {
            if (Session["username"] == null)
                return RedirectToRoute("Autentication", new { controller = "User" });
            EBPOMServiceClient obj = new EBPOMServiceClient();
            Produsen_Vaksin newDataProdusen = null;
            Produsen_Vaksin cekStatus = obj.GetProdusenVaksinByNoReg(no_registrasi);
             BPOM_Vaksin newData = new BPOM_Vaksin
            {
                create_at = create_at,
                no_registrasi = no_registrasi,
                kemasan = cekStatus.kemasan,
                jumlah = cekStatus.jumlah,
                status = status
             };
            if (cekStatus != null)
            {
                if (!cekStatus.status.Equals("Not Reported"))
                {
                    newDataProdusen = new Produsen_Vaksin
                    {
                        create_at = create_at,
                        no_registrasi = no_registrasi,
                        kemasan = cekStatus.kemasan,
                        jumlah = cekStatus.jumlah,
                        status = status
                    };
                    obj.UpdateProdusenVaksin(newDataProdusen);
                }
            }
            obj.UpdateVaksin(newData);
            /*
            ViewBag.no_registrasi = no_registrasi;
            ViewBag.status = status;
            */
            Models.ListViewModel viewmodel = new Models.ListViewModel
            {
                bpom_vaksins = obj.GetVaksin(),
                produsens = obj.GetListProdusen()
            };
            return View(viewmodel);
        }

        public ActionResult CheckLogArrivalVaccine()
        {
            if (Session["username"] == null)
                return RedirectToRoute("Autentication", new { controller = "User" });
            EBPOMServiceClient obj = new EBPOMServiceClient();
            Models.ListViewModel viewmodel = new Models.ListViewModel
            {
                LogsArrivals = obj.GetLogArrivalVaccine(),
                produsens = obj.GetListProdusen(),
                rumahSakits = obj.GetListRumahSakit(),
                rsVaksins = obj.GetVaksinRS()
            };
            return View(viewmodel);
        }

        public ActionResult CheckLogVaccineUse()
        {
            if (Session["username"] == null)
                return RedirectToRoute("Autentication", new { controller = "User" });
            EBPOMServiceClient obj = new EBPOMServiceClient();
            
            Models.ListViewModel viewmodel = new Models.ListViewModel
            {
                logUses = obj.GetLogVaccineUse(),
                masyarakts = obj.GetListMasyarakat(),
                pasiens = obj.GetListPasien(),
                produsens = obj.GetListProdusen(),
                rumahSakits = obj.GetListRumahSakit(),
                rsVaksins = obj.GetVaksinRS()
            };
            return View(viewmodel);
        }

    }
}

TrackingVaksinApp/Views/BPOMVaksin/CheckLogArrivalVaccine.cshtml
@model TrackingVaksinApp.Models.ListViewModel

@{
    ViewBag.Title = "CheckLogArrivalVaccine";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link href="https://cdn.datatables.net/1.10.24/css/dataTables.bootstrap4.min.css" rel="stylesheet" />

<h2>CheckLogArrivalVaccine</h2>

<h4 class="alert alert-info">Vaksin (@Model.LogsArrivals.Count()) Data</h4>
<table id="example" class="table table-bordered" style="width:100%">
    <thead>
        <tr>
            <th>
                Tanggal Lapor
            </th>
            <th>
                Nama RUmah Sakit
            </th>
            <th>
                Nama Produsen
            </th>
            <th>
                No Registrasi
            </th>
            <th>Tindakan</th>
        </tr>
        </thead>
    <tbody>
        @foreach (var item in Model.LogsArrivals)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.create_at)
                </td>
                <td>
                    @Model.rumahSakits.FirstOrDefault(X => X.id == item.id_RumahSakit).Nama.ToString()
                </td>
                <td>
                    @Model.produsens.FirstOrDefault(X => X.id == item.id_produsen).Nama.ToString()
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.no_registrasi)
                </td>
                <td>
                    <button title="Lihat Detail" type="button" class="btn btn-sm btn-primary ml-4" data-toggle="modal" data-target="#exampleModal-@item.no_registrasi">
                        <i class="fas fa-eye"></i>
                    </button>
                </td>
            </tr>

            <div class="modal fade" id="exampleModal-@item.no_registrasi" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">Log Kedatangan Vaksin</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <div class="pt-2 mr-2">
                                <div class="card ml-4" style="width: 25rem;">
                                    <ul class="list-group list-group-flush">
                                        <li class="list-group-item"> <label for="@item.create_at">Dilapor Pada : </label> @item.create_at</li>
                                        <li class="list-group-item"> <label for="@item.no_registrasi">No Registrasi : </label> @item.no_registrasi</li>
                                        <li class="list-group-item"><label for="@item.id_produsen">Nama Produsen : </label> @Model.produsens.FirstOrDefault(X => X.id == item.id_produsen).Nama.ToString()</li>
                                        <li class="list-group-item"><label for="@item.id_RumahSakit">Nama Rumah Sakit : </label> @Model.rumahSakits.FirstOrDefault(X => X.id == item.id_RumahSakit).Nama.ToString()</li>
                                        <H4>Detail Vaksin</H4>
                                        @foreach (var detailVaksin in Model.rsVaksins.Where(X => X.no_registrasi.Equals(item.no_registrasi)))
                                        {
                                            <li class="list-group-item"><label for="@detailVaksin.kemasan">Kemasan : </label> @detailVaksin.kemasan</li>
                                            <li class="list-group-item"><label for="@detailVaksin.jumlah">Jumlah : </label> @detailVaksin.jumlah</li>
                                            <li class="list-group-item"><label for="@detailVaksin.kode_ref">Kode Refrensi : </label> @detailVaksin.kode_ref</li>
                                        }
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        </div>
                    </div>
                </div>
            </div>
        }
    </tbody>

</table>

<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script src="https://cdn.datatables.net/1.10.24/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.24/js/dataTables.bootstrap4.min.js"></script>

<script>
    $(document).ready(function () {
        $('#example').DataTable();
    });
</script>

TrackingVaksinApp/Views/BPOMVaksin/CheckLogVaccineUse.cshtml
@model TrackingVaksinApp.Models.ListViewModel

@{
    ViewBag.Title = "CheckLogVaccineUse";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>CheckLogVaccineUse</h2>
<link rel="stylesheet" href="~/Content/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css">
<link href="https://cdn.datatables.net/1.10.24/css/dataTables.bootstrap4.min.css" rel="stylesheet" />
<table id="example" class="table table-bordered" style="width:100%">
    <thead>
        <tr>
            <th>
                NIK
            </th>
            <th>
                No Rekam Medis
            </th>
            <th>
                Tanggal Lapor
            </th>
            <th>
                Nama Rumah Sakit
            </th>
            <th>
                No Registrasi Vaksin
            </th>
            <th>Tindakan</th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model.logUses)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.NIK)
                    <sup>
                        <button title="Lihat Detail Pasien" type="button" class="text-success"  data-toggle="modal" data-target="#exampleModal-@item.NIK-detail">
                        <span class="text-success">
                            <i class="fas fa-eye"></i>
                        </span>
                        </button>
                    </sup>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.No_RekMedis)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.create_at)
                </td>
                <td>
                    @Model.rumahSakits.FirstOrDefault(X => X.id == item.id_RumahSakit).Nama.ToString()
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.no_registrasi)
                </td>
                <td>
                    <button title="Lihat Detail" type="button" class="btn btn-sm btn-primary ml-4" data-toggle="modal" data-target="#exampleModal-@item.NIK">
                        <i class="fas fa-eye"></i>
                    </button>
                </td>
            </tr>



            <!--Detail All by Modal-->
            <div class="modal fade" id="exampleModal-@item.NIK" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">Log Penggunaan Vaksin</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <div class="pt-2 mr-2">
                                <div class="card ml-4" style="width: 25rem;">
                                    <ul class="list-group list-group-flush">
                                        <li class="list-group-item"> <label for="@item.create_at">Dilapor Pada : </label> @item.create_at</li>
                                        <li class="list-group-item"><label for="@item.id_RumahSakit">Nama Rumah Sakit : </label> @Model.rumahSakits.FirstOrDefault(X => X.id == item.id_RumahSakit).Nama.ToString()</li>
                                        <H4>Detail Pasien</H4>
                                        @foreach (var detailPasien in Model.pasiens.Where(X => X.No_RekMedis.Equals(item.No_RekMedis)))
                                        {
                                            <li class="list-group-item"><label for="@detailPasien.No_RekMedis">NO Rekam Medis : </label> @detailPasien.No_RekMedis</li>
                                            <li class="list-group-item"><label for="@detailPasien.NIK">NIK : </label> @detailPasien.NIK</li>
                                        }
                                        <H4>Detail Vaksin</H4>
                                        @foreach (var detailVaksin in Model.rsVaksins.Where(X => X.no_registrasi.Equals(item.no_registrasi)))
                                        {
                                            <li class="list-group-item"> <label for="@detailVaksin.no_registrasi">No Registrasi : </label> @detailVaksin.no_registrasi</li>
                                            <li class="list-group-item"><label for="@detailVaksin.kemasan">Kemasan : </label> @detailVaksin.kemasan</li>
                                            <li class="list-group-item"><label for="@detailVaksin.jumlah">Jumlah : </label> @detailVaksin.jumlah</li>
                                            <li class="list-group-item"><label for="@detailVaksin.kode_ref">Kode Refrensi : </label> @detailVaksin.kode_ref</li>
                                        }
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        </div>
                    </div>
                </div>
            </div>


            <!--Detail Pasien-->
            <div class="modal fade" id="exampleModal-@item.NIK-detail" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">Detail Pasien</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <div class="pt-2 mr-2">
                                <div class="card ml-4" style="width: 25rem;">
                                    <ul class="list-group list-group-flush">
                                        @foreach (var detailMasyarakat in Model.masyarakts.Where(X => X.NIK.Equals(item.NIK)))
                                        {
                                            DateTime tglLahir = (DateTime)detailMasyarakat.TglLahir;
                                            string JenisKelamin = detailMasyarakat.JK.Equals("L") ? "Laki-Laki" : "Wanita";
                                            <li class="list-group-item"> <label for="@detailMasyarakat.NIK">NIK : </label> @detailMasyarakat.NIK</li>
                                            <li class="list-group-item"><label for="@detailMasyarakat.Nama">Nama : </label> @detailMasyarakat.Nama</li>
                                            <li class="list-group-item"><label for="@detailMasyarakat.JK">Jenis Kelamin : </label> @JenisKelamin</li>
                                            <li class="list-group-item"><label for="@tglLahir">Tanggal Lahir: </label> @tglLahir.ToString("dd MMMM yyyy")</li>
                                        }
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        </div>
                    </div>
                </div>
            </div>
        }
    </tbody>
</table>

<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script src="https://cdn.datatables.net/1.10.24/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.24/js/dataTables.bootstrap4.min.js"></script>

<script>
    $(document).ready(function () {
        $('#example').DataTable();
    });
</script>

TrackingVaksinApp/Views/BPOMVaksin/Index.cshtml
@model TrackingVaksinApp.Models.ListViewModel

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link href="https://cdn.datatables.net/1.10.24/css/dataTables.bootstrap4.min.css" rel="stylesheet" />

<h2>Index</h2>

<h4 class="alert alert-info">Vaksin (@Model.bpom_vaksins.Count()) Data</h4>
<table id="example" class="table table-bordered" style="width:100%">
    <thead>
        <tr>
            <th>
                Create At
            </th>
            <th>
                No Registrasi
            </th>
            <th>
                Nama Produsen
            </th>
            <th>
                Status
            </th>
            <th>Action</th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model.bpom_vaksins)
        {
            string clTr;
            if (item.status.Equals("Invalid"))
            {
                clTr = "table-danger";
            }
            else
            {
                clTr = "";
            }
            <tr class="@clTr">
                <td>
                    @Html.DisplayFor(modelItem => item.create_at)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.no_registrasi)
                </td>
                <td>
                    @Model.produsens.FirstOrDefault(X => X.id == item.id_produsen).Nama.ToString()
                </td>
                <td>
                    @if (item.status.Equals("Valid"))
                    {
                        <span class="badge badge-success">@item.status</span>
                    }
                    else
                    {
                        <span class="badge badge-danger">@item.status</span>
                    }
                </td>
                <td )>
                    @using (Html.BeginForm("index", "BPOMVaksin"))
                    {
                        <input type="hidden" name="no_registrasi" value="@Html.DisplayFor(modelItem => item.no_registrasi)" />
                        <input type="hidden" name="create_at" value="@Html.DisplayFor(modelItem => item.create_at)" />
                        if (item.status.Equals("Invalid"))
                        {
                            <button title="Lihat Detail" type="button" class="btn btn-sm btn-primary ml-4" data-toggle="modal" data-target="#exampleModal-@item.no_registrasi">
                                <i class="fas fa-eye"></i>
                            </button>
                            <button type="submit" name="status" onclick="return confirm('Are you Sure to Validate?')" value="Valid" title="Validasi Vaksin" class="btn btn-danger btn-sm"> <i class="fas fa-power-off"></i></button>
                        }
                        else
                        {
                            <button title="Lihat Detail" type="button" class="btn btn-sm btn-primary ml-4" data-toggle="modal" data-target="#exampleModal-@item.no_registrasi">
                                <i class="fas fa-eye"></i>
                            </button>
                            <button type="submit" name="status" onclick="return confirm('Are you Sure to Devalidate?')" value="Invalid" title="DeValidasi Vaksin" class="btn btn-success btn-sm"><i class="fas fa-power-off"></i></button>
                        }

                    }
                </td>
            </tr>


            <div class="modal fade" id="exampleModal-@item.no_registrasi" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">Detail Vaksin</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <div class="pt-2 mr-2">
                                <div class="card ml-4" style="width: 25rem;">
                                    <ul class="list-group list-group-flush">
                                        <li class="list-group-item"> <label for="@item.create_at">Dibuat Pada : </label> @item.create_at</li>
                                        <li class="list-group-item"> <label for="@item.no_registrasi">No Registrasi : </label> @item.no_registrasi</li>
                                        <li class="list-group-item"><label for="@item.id_produsen">Nama Produsen : </label> @Model.produsens.FirstOrDefault(X => X.id == item.id_produsen).Nama.ToString()</li>
                                        <li class="list-group-item"><label for="@item.id_produsen">Kemasan : </label> @item.kemasan</li>
                                        <li class="list-group-item"><label for="@item.id_produsen">Jumlah : </label> @item.jumlah</li>
                                        @if (item.status.Equals("Invalid"))
                                        {
                                            <li class="list-group-item"><label for="@item.status">Status : </label> <span class="badge badge-danger"> @item.status </span> </li>
                                        }
                                        else
                                        {
                                            <li class="list-group-item"><label for="@item.status">Status : </label> <span class="badge badge-success"> @item.status </span> </li>
                                        }
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        </div>
                    </div>
                </div>
            </div>
        }
        </tbody>

</table>





<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script src="https://cdn.datatables.net/1.10.24/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.24/js/dataTables.bootstrap4.min.js"></script>


<script>
    $(document).ready(function () {
        $('#example').DataTable();
    });
</script>

TrackingVaksinApp/Views/BPOMVaksin/Test.cshtml
@{
    ViewBag.Title = "Test";
    Layout = null;
}

<h2>Test</h2>

<div>
    <h4>BPOM_Vaksin</h4>
    <hr />
    <dl class="dl-horizontal">
        <p>No Registrasi = @ViewBag.no_registrasi</p>
        <p>Status = @ViewBag.status</p>

    </dl>
</div>